"""
    You are given two strings s and t.

    String t is generated by random shuffling string s and then add one more letter at a random position.

    Return the letter that was added to t.
"""

class FindTheDifference(object):
    def findTheDifference(self, s, t):
        sLetters = {}
        for i in s:
            if i in sLetters:
                sLetters[i] += 1
            else:
                sLetters[i] = 1
        for i in t:
            if i not in sLetters:
                return i
            else:
                sLetters[i] -= 1
                if sLetters[i] == 0:
                    del sLetters[i]